SET DEFINE OFF

PROMPT Applying migration: add media_assets and users.avatar_media_id...

DECLARE
    l_exists NUMBER;
BEGIN
    SELECT COUNT(*)
      INTO l_exists
      FROM user_tab_cols
     WHERE table_name = 'USERS'
       AND column_name = 'AVATAR_MEDIA_ID';

    IF l_exists = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE users ADD (avatar_media_id NUMBER)';
        DBMS_OUTPUT.PUT_LINE('Added USERS.AVATAR_MEDIA_ID column.');
    END IF;
END;
/

DECLARE
    l_exists NUMBER;
BEGIN
    SELECT COUNT(*)
      INTO l_exists
      FROM user_tables
     WHERE table_name = 'MEDIA_ASSETS';

    IF l_exists = 0 THEN
        EXECUTE IMMEDIATE '
            CREATE TABLE media_assets (
                media_id               NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                uploader_user_id       NUMBER             NOT NULL,
                owner_type             VARCHAR2(30 CHAR)  NOT NULL,
                owner_id               NUMBER             NOT NULL,
                file_name              VARCHAR2(120 CHAR) NOT NULL,
                original_file_name     VARCHAR2(255 CHAR),
                mime_type              VARCHAR2(100 CHAR) NOT NULL,
                file_ext               VARCHAR2(20 CHAR),
                file_size              NUMBER             DEFAULT 0        NOT NULL,
                storage_path           VARCHAR2(255 CHAR) NOT NULL,
                public_url             VARCHAR2(255 CHAR) NOT NULL,
                file_content           BLOB               NOT NULL,
                sort_order             NUMBER             DEFAULT 1        NOT NULL,
                status                 VARCHAR2(20 CHAR)  DEFAULT ''ACTIVE'' NOT NULL,
                create_time            DATE               DEFAULT SYSDATE  NOT NULL,
                update_time            DATE               DEFAULT SYSDATE  NOT NULL,
                delete_time            DATE,
                CONSTRAINT pk_media_assets PRIMARY KEY (media_id),
                CONSTRAINT uq_media_assets_file_name UNIQUE (file_name),
                CONSTRAINT fk_media_assets_uploader
                    FOREIGN KEY (uploader_user_id) REFERENCES users (user_id),
                CONSTRAINT ck_media_assets_owner_type CHECK (
                    owner_type IN (''USER_AVATAR'', ''QUESTION'', ''ANSWER'')
                ),
                CONSTRAINT ck_media_assets_status CHECK (
                    status IN (''ACTIVE'', ''DELETED'')
                ),
                CONSTRAINT ck_media_assets_file_size CHECK (file_size BETWEEN 0 AND 52428800),
                CONSTRAINT ck_media_assets_sort_order CHECK (sort_order >= 1),
                CONSTRAINT ck_media_assets_delete_time CHECK (
                    delete_time IS NULL OR delete_time >= create_time
                )
            )
        ';
        DBMS_OUTPUT.PUT_LINE('Created MEDIA_ASSETS table.');
    END IF;
END;
/

DECLARE
    l_exists NUMBER;
BEGIN
    SELECT COUNT(*)
      INTO l_exists
      FROM user_tab_cols
     WHERE table_name = 'MEDIA_ASSETS'
       AND column_name = 'FILE_CONTENT';

    IF l_exists = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE media_assets ADD (file_content BLOB)';
        DBMS_OUTPUT.PUT_LINE('Added MEDIA_ASSETS.FILE_CONTENT column.');
    END IF;
END;
/

UPDATE media_assets
   SET file_content = EMPTY_BLOB()
 WHERE file_content IS NULL;

UPDATE media_assets
   SET public_url = '/api/media/files/' || file_name,
       storage_path = 'db://media_assets/' || file_name,
       update_time = SYSDATE
 WHERE public_url LIKE '/uploads/%'
    OR storage_path LIKE 'uploads/%';

DECLARE
    l_nullable VARCHAR2(1);
BEGIN
    SELECT nullable
      INTO l_nullable
      FROM user_tab_cols
     WHERE table_name = 'MEDIA_ASSETS'
       AND column_name = 'FILE_CONTENT';

    IF l_nullable = 'Y' THEN
        EXECUTE IMMEDIATE 'ALTER TABLE media_assets MODIFY (file_content NOT NULL)';
        DBMS_OUTPUT.PUT_LINE('Set MEDIA_ASSETS.FILE_CONTENT NOT NULL.');
    END IF;
END;
/

DECLARE
    l_exists NUMBER;
BEGIN
    SELECT COUNT(*)
      INTO l_exists
      FROM user_constraints
     WHERE table_name = 'MEDIA_ASSETS'
       AND constraint_name = 'UQ_MEDIA_ASSETS_FILE_NAME';

    IF l_exists = 0 THEN
        EXECUTE IMMEDIATE '
            ALTER TABLE media_assets
            ADD CONSTRAINT uq_media_assets_file_name UNIQUE (file_name)
        ';
        DBMS_OUTPUT.PUT_LINE('Added UQ_MEDIA_ASSETS_FILE_NAME.');
    END IF;
END;
/

DECLARE
    l_exists NUMBER;
BEGIN
    SELECT COUNT(*)
      INTO l_exists
      FROM user_constraints
     WHERE table_name = 'USERS'
       AND constraint_name = 'FK_USERS_AVATAR_MEDIA';

    IF l_exists = 0 THEN
        EXECUTE IMMEDIATE '
            ALTER TABLE users
            ADD CONSTRAINT fk_users_avatar_media
            FOREIGN KEY (avatar_media_id) REFERENCES media_assets (media_id)
        ';
        DBMS_OUTPUT.PUT_LINE('Added FK_USERS_AVATAR_MEDIA.');
    END IF;
END;
/

DECLARE
    l_exists NUMBER;
BEGIN
    SELECT COUNT(*)
      INTO l_exists
      FROM user_indexes
     WHERE table_name = 'USERS'
       AND index_name = 'IDX_USERS_AVATAR_MEDIA_ID';

    IF l_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE INDEX idx_users_avatar_media_id ON users (avatar_media_id)';
        DBMS_OUTPUT.PUT_LINE('Added IDX_USERS_AVATAR_MEDIA_ID.');
    END IF;
END;
/

DECLARE
    l_exists NUMBER;
BEGIN
    SELECT COUNT(*)
      INTO l_exists
      FROM user_indexes
     WHERE table_name = 'MEDIA_ASSETS'
       AND index_name = 'IDX_MEDIA_ASSETS_UPLOADER_ID';

    IF l_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE INDEX idx_media_assets_uploader_id ON media_assets (uploader_user_id)';
        DBMS_OUTPUT.PUT_LINE('Added IDX_MEDIA_ASSETS_UPLOADER_ID.');
    END IF;
END;
/

DECLARE
    l_exists NUMBER;
BEGIN
    SELECT COUNT(*)
      INTO l_exists
      FROM user_indexes
     WHERE table_name = 'MEDIA_ASSETS'
       AND index_name = 'IDX_MEDIA_ASSETS_OWNER_REF';

    IF l_exists = 0 THEN
        EXECUTE IMMEDIATE '
            CREATE INDEX idx_media_assets_owner_ref
            ON media_assets (owner_type, owner_id, status, sort_order)
        ';
        DBMS_OUTPUT.PUT_LINE('Added IDX_MEDIA_ASSETS_OWNER_REF.');
    END IF;
END;
/

DECLARE
    l_exists NUMBER;
BEGIN
    SELECT COUNT(*)
      INTO l_exists
      FROM user_indexes
     WHERE table_name = 'MEDIA_ASSETS'
       AND index_name = 'IDX_MEDIA_ASSETS_CREATE_TIME';

    IF l_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE INDEX idx_media_assets_create_time ON media_assets (create_time)';
        DBMS_OUTPUT.PUT_LINE('Added IDX_MEDIA_ASSETS_CREATE_TIME.');
    END IF;
END;
/

COMMIT;

PROMPT Migration completed successfully.
