PROMPT Creating ANSWER_COMMENTS...
CREATE TABLE answer_comments (
    comment_id         NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    answer_id          NUMBER             NOT NULL,
    user_id            NUMBER             NOT NULL,
    parent_comment_id  NUMBER,
    root_comment_id    NUMBER,
    reply_to_user_id   NUMBER,
    content            CLOB               NOT NULL,
    comment_level      NUMBER             DEFAULT 1        NOT NULL,
    status             VARCHAR2(20 CHAR)  DEFAULT 'ACTIVE' NOT NULL,
    reply_count        NUMBER             DEFAULT 0        NOT NULL,
    create_time        DATE               DEFAULT SYSDATE  NOT NULL,
    update_time        DATE               DEFAULT SYSDATE  NOT NULL,
    delete_time        DATE,
    CONSTRAINT pk_answer_comments PRIMARY KEY (comment_id),
    CONSTRAINT fk_answer_comments_answer
        FOREIGN KEY (answer_id) REFERENCES answers (answer_id),
    CONSTRAINT fk_answer_comments_user
        FOREIGN KEY (user_id) REFERENCES users (user_id),
    CONSTRAINT fk_answer_comments_parent
        FOREIGN KEY (parent_comment_id) REFERENCES answer_comments (comment_id),
    CONSTRAINT fk_answer_comments_root
        FOREIGN KEY (root_comment_id) REFERENCES answer_comments (comment_id),
    CONSTRAINT fk_answer_comments_reply_user
        FOREIGN KEY (reply_to_user_id) REFERENCES users (user_id),
    CONSTRAINT ck_answer_comments_level CHECK (comment_level >= 1),
    CONSTRAINT ck_answer_comments_status CHECK (status IN ('ACTIVE', 'HIDDEN', 'DELETED')),
    CONSTRAINT ck_answer_comments_reply_count CHECK (reply_count >= 0),
    CONSTRAINT ck_answer_comments_delete_time CHECK (
        delete_time IS NULL OR delete_time >= create_time
    )
);

CREATE INDEX idx_answer_comments_answer_id ON answer_comments (answer_id);
CREATE INDEX idx_answer_comments_user_id ON answer_comments (user_id);
CREATE INDEX idx_answer_comments_parent_id ON answer_comments (parent_comment_id);
CREATE INDEX idx_answer_comments_root_id ON answer_comments (root_comment_id);
CREATE INDEX idx_answer_comments_create_time ON answer_comments (create_time);
