-- create_tables.sql
-- Oracle AI Database 26ai schema for the AI QA system

SET DEFINE OFF

-- 说明：本脚本定义问知社区的核心业务 schema。
-- 重点体现：用户与权限、问答内容、社区互动、媒体 BLOB、AI 调用日志、用户画像与推荐。

PROMPT Creating USERS...
-- 用户主表：保存登录账号、展示资料、角色和状态。
-- role 用于区分普通用户和管理员；status 用于支持封禁、停用和锁定。
CREATE TABLE users (
    user_id          NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    username         VARCHAR2(50 CHAR)  NOT NULL,
    password_hash    VARCHAR2(100 CHAR) NOT NULL,
    nickname         VARCHAR2(50 CHAR),
    email            VARCHAR2(100 CHAR),
    phone            VARCHAR2(20 CHAR),
    role             VARCHAR2(20 CHAR)  DEFAULT 'USER'   NOT NULL,
    status           VARCHAR2(20 CHAR)  DEFAULT 'ACTIVE' NOT NULL,
    register_time    DATE               DEFAULT SYSDATE  NOT NULL,
    last_login_time  DATE,
    avatar_media_id  NUMBER,
    CONSTRAINT pk_users PRIMARY KEY (user_id),
    CONSTRAINT uq_users_username UNIQUE (username),
    CONSTRAINT ck_users_role CHECK (role IN ('USER', 'ADMIN')),
    CONSTRAINT ck_users_status CHECK (status IN ('ACTIVE', 'INACTIVE', 'LOCKED', 'DISABLED'))
);

PROMPT Creating CATEGORIES...
-- 一级分类表：用于首页筛选和问题归类，数量应保持少而稳定。
-- 更细的主题应放在 TAGS 中，避免分类体系膨胀。
CREATE TABLE categories (
    category_id     NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    category_name   VARCHAR2(50 CHAR)  NOT NULL,
    description     VARCHAR2(200 CHAR),
    status          VARCHAR2(20 CHAR)  DEFAULT 'ACTIVE' NOT NULL,
    CONSTRAINT pk_categories PRIMARY KEY (category_id),
    CONSTRAINT uq_categories_name UNIQUE (category_name),
    CONSTRAINT ck_categories_status CHECK (status IN ('ACTIVE', 'INACTIVE'))
);

PROMPT Creating TAGS...
-- 标签表：用于描述问题细分主题，可由系统、用户、AI 或管理员产生。
-- 标签比分类更灵活，是用户画像和推荐算法的重要输入。
CREATE TABLE tags (
    tag_id          NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    tag_name        VARCHAR2(50 CHAR) NOT NULL,
    source          VARCHAR2(20 CHAR) DEFAULT 'SYSTEM' NOT NULL,
    status          VARCHAR2(20 CHAR) DEFAULT 'ACTIVE' NOT NULL,
    description     VARCHAR2(200 CHAR),
    create_user_id  NUMBER,
    create_time     DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT pk_tags PRIMARY KEY (tag_id),
    CONSTRAINT uq_tags_name UNIQUE (tag_name),
    CONSTRAINT fk_tags_create_user
        FOREIGN KEY (create_user_id) REFERENCES users (user_id),
    CONSTRAINT ck_tags_source CHECK (source IN ('SYSTEM', 'USER', 'AI', 'ADMIN')),
    CONSTRAINT ck_tags_status CHECK (status IN ('ACTIVE', 'PENDING', 'DISABLED'))
);

PROMPT Creating MEDIA_ASSETS...
-- 统一媒体资源表：头像、问题配图、回答配图都存放在这里。
-- file_content 使用 BLOB 保存图片二进制，file_size 通过 CHECK 限制为 50MB 以内。
CREATE TABLE media_assets (
    media_id               NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    uploader_user_id       NUMBER             NOT NULL,
    owner_type             VARCHAR2(30 CHAR)  NOT NULL,
    owner_id               NUMBER             NOT NULL,
    file_name              VARCHAR2(120 CHAR) NOT NULL,
    original_file_name     VARCHAR2(255 CHAR),
    mime_type              VARCHAR2(100 CHAR) NOT NULL,
    file_ext               VARCHAR2(20 CHAR),
    file_size              NUMBER             DEFAULT 0        NOT NULL,
    storage_path           VARCHAR2(255 CHAR) NOT NULL,
    public_url             VARCHAR2(255 CHAR) NOT NULL,
    file_content           BLOB               NOT NULL,
    sort_order             NUMBER             DEFAULT 1        NOT NULL,
    status                 VARCHAR2(20 CHAR)  DEFAULT 'ACTIVE' NOT NULL,
    create_time            DATE               DEFAULT SYSDATE  NOT NULL,
    update_time            DATE               DEFAULT SYSDATE  NOT NULL,
    delete_time            DATE,
    CONSTRAINT pk_media_assets PRIMARY KEY (media_id),
    CONSTRAINT uq_media_assets_file_name UNIQUE (file_name),
    CONSTRAINT fk_media_assets_uploader
        FOREIGN KEY (uploader_user_id) REFERENCES users (user_id),
    CONSTRAINT ck_media_assets_owner_type CHECK (
        owner_type IN ('USER_AVATAR', 'QUESTION', 'ANSWER')
    ),
    CONSTRAINT ck_media_assets_status CHECK (
        status IN ('ACTIVE', 'DELETED')
    ),
    CONSTRAINT ck_media_assets_file_size CHECK (file_size BETWEEN 0 AND 52428800),
    CONSTRAINT ck_media_assets_sort_order CHECK (sort_order >= 1),
    CONSTRAINT ck_media_assets_delete_time CHECK (
        delete_time IS NULL OR delete_time >= create_time
    )
);

PROMPT Linking USERS avatar to MEDIA_ASSETS...
ALTER TABLE users
ADD CONSTRAINT fk_users_avatar_media
    FOREIGN KEY (avatar_media_id) REFERENCES media_assets (media_id);

PROMPT Creating QUESTIONS...
-- 问题主表：保存提问者、分类、标题、正文和问题状态。
-- view_count、favorite_count、answer_count 是冗余统计字段，由触发器和存储过程同步维护。
CREATE TABLE questions (
    question_id      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    user_id          NUMBER             NOT NULL,
    category_id      NUMBER             NOT NULL,
    title            VARCHAR2(200 CHAR) NOT NULL,
    content          CLOB               NOT NULL,
    ask_time         DATE               DEFAULT SYSDATE NOT NULL,
    status           VARCHAR2(20 CHAR)  DEFAULT 'OPEN' NOT NULL,
    accepted_answer_id NUMBER,
    view_count       NUMBER             DEFAULT 0       NOT NULL,
    favorite_count   NUMBER             DEFAULT 0       NOT NULL,
    answer_count     NUMBER             DEFAULT 0       NOT NULL,
    CONSTRAINT pk_questions PRIMARY KEY (question_id),
    CONSTRAINT fk_questions_user
        FOREIGN KEY (user_id) REFERENCES users (user_id),
    CONSTRAINT fk_questions_category
        FOREIGN KEY (category_id) REFERENCES categories (category_id),
    CONSTRAINT ck_questions_status CHECK (status IN ('OPEN', 'RESOLVED', 'CLOSED', 'ARCHIVED', 'DELETED')),
    CONSTRAINT ck_questions_view_count CHECK (view_count >= 0),
    CONSTRAINT ck_questions_favorite_count CHECK (favorite_count >= 0),
    CONSTRAINT ck_questions_answer_count CHECK (answer_count >= 0)
);

PROMPT Creating ANSWERS...
-- 回答表：同时支持 AI 回答、人工回答和系统回答。
-- ck_answers_user_presence 保证人工回答必须有 user_id，而 AI/SYSTEM 回答不绑定用户。
CREATE TABLE answers (
    answer_id          NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    question_id        NUMBER             NOT NULL,
    user_id            NUMBER,
    answer_type        VARCHAR2(20 CHAR)  NOT NULL,
    provider_name      VARCHAR2(50 CHAR),
    content            CLOB               NOT NULL,
    generate_time      DATE               DEFAULT SYSDATE NOT NULL,
    status             VARCHAR2(20 CHAR)  DEFAULT 'ACTIVE' NOT NULL,
    delete_time        DATE,
    model_name         VARCHAR2(50 CHAR),
    confidence_score   NUMBER(5,2),
    like_count         NUMBER             DEFAULT 0       NOT NULL,
    dislike_count      NUMBER             DEFAULT 0       NOT NULL,
    avg_rating         NUMBER(3,2),
    CONSTRAINT pk_answers PRIMARY KEY (answer_id),
    CONSTRAINT uq_answers_question_answer UNIQUE (question_id, answer_id),
    CONSTRAINT fk_answers_question
        FOREIGN KEY (question_id) REFERENCES questions (question_id),
    CONSTRAINT fk_answers_user
        FOREIGN KEY (user_id) REFERENCES users (user_id),
    CONSTRAINT ck_answers_type CHECK (answer_type IN ('AI', 'MANUAL', 'SYSTEM')),
    CONSTRAINT ck_answers_user_presence CHECK (
        (answer_type = 'MANUAL' AND user_id IS NOT NULL)
        OR (answer_type IN ('AI', 'SYSTEM') AND user_id IS NULL)
    ),
    CONSTRAINT ck_answers_status CHECK (status IN ('ACTIVE', 'HIDDEN', 'DELETED')),
    CONSTRAINT ck_answers_delete_time CHECK (
        delete_time IS NULL OR delete_time >= generate_time
    ),
    CONSTRAINT ck_answers_confidence CHECK (
        confidence_score IS NULL OR (confidence_score >= 0 AND confidence_score <= 100)
    ),
    CONSTRAINT ck_answers_like_count CHECK (like_count >= 0),
    CONSTRAINT ck_answers_dislike_count CHECK (dislike_count >= 0),
    CONSTRAINT ck_answers_avg_rating CHECK (
        avg_rating IS NULL OR (avg_rating >= 0 AND avg_rating <= 5)
    )
);

ALTER TABLE questions
    -- 复合外键保证“采纳答案”必须属于当前问题，避免把其他问题的答案误采纳。
    ADD CONSTRAINT fk_questions_accepted_answer
        FOREIGN KEY (question_id, accepted_answer_id)
        REFERENCES answers (question_id, answer_id);

PROMPT Creating QUESTION_TAGS...
-- 问题与标签的多对多关系表。
-- source 和 confidence_score 用于区分用户选择、用户创建、AI 匹配、AI 创建和管理员调整。
CREATE TABLE question_tags (
    qt_id           NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    question_id     NUMBER NOT NULL,
    tag_id          NUMBER NOT NULL,
    source          VARCHAR2(30 CHAR) DEFAULT 'USER_SELECTED' NOT NULL,
    confidence_score NUMBER(5,2),
    create_time     DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT pk_question_tags PRIMARY KEY (qt_id),
    CONSTRAINT fk_question_tags_question
        FOREIGN KEY (question_id) REFERENCES questions (question_id),
    CONSTRAINT fk_question_tags_tag
        FOREIGN KEY (tag_id) REFERENCES tags (tag_id),
    CONSTRAINT uq_question_tags_pair UNIQUE (question_id, tag_id),
    CONSTRAINT ck_question_tags_source CHECK (
        source IN ('USER_SELECTED', 'USER_CREATED', 'AI_MATCHED', 'AI_CREATED', 'ADMIN_ADJUSTED')
    ),
    CONSTRAINT ck_question_tags_confidence CHECK (
        confidence_score IS NULL OR (confidence_score >= 0 AND confidence_score <= 100)
    )
);

PROMPT Creating ANSWER_FEEDBACK...
CREATE TABLE answer_feedback (
    feedback_id      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    answer_id        NUMBER             NOT NULL,
    user_id          NUMBER             NOT NULL,
    is_like          VARCHAR2(10 CHAR)  NOT NULL,
    rating           NUMBER(2,1),
    comment_text     VARCHAR2(500 CHAR),
    feedback_time    DATE               DEFAULT SYSDATE NOT NULL,
    CONSTRAINT pk_answer_feedback PRIMARY KEY (feedback_id),
    CONSTRAINT fk_answer_feedback_answer
        FOREIGN KEY (answer_id) REFERENCES answers (answer_id),
    CONSTRAINT fk_answer_feedback_user
        FOREIGN KEY (user_id) REFERENCES users (user_id),
    CONSTRAINT ck_answer_feedback_like CHECK (is_like IN ('Y', 'N')),
    CONSTRAINT ck_answer_feedback_rating CHECK (
        rating IS NULL OR (rating >= 0 AND rating <= 5)
    ),
    CONSTRAINT uq_answer_feedback_answer_user UNIQUE (answer_id, user_id)
);

PROMPT Creating ANSWER_COMMENTS...
-- 回答评论表：通过 parent_comment_id/root_comment_id 支持楼中楼回复。
-- 删除采用软删除，保留评论关系链，前端可展示“原评论/回复已删除”。
CREATE TABLE answer_comments (
    comment_id         NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    answer_id          NUMBER             NOT NULL,
    user_id            NUMBER             NOT NULL,
    parent_comment_id  NUMBER,
    root_comment_id    NUMBER,
    reply_to_user_id   NUMBER,
    content            CLOB               NOT NULL,
    comment_level      NUMBER             DEFAULT 1        NOT NULL,
    status             VARCHAR2(20 CHAR)  DEFAULT 'ACTIVE' NOT NULL,
    reply_count        NUMBER             DEFAULT 0        NOT NULL,
    create_time        DATE               DEFAULT SYSDATE  NOT NULL,
    update_time        DATE               DEFAULT SYSDATE  NOT NULL,
    delete_time        DATE,
    CONSTRAINT pk_answer_comments PRIMARY KEY (comment_id),
    CONSTRAINT fk_answer_comments_answer
        FOREIGN KEY (answer_id) REFERENCES answers (answer_id),
    CONSTRAINT fk_answer_comments_user
        FOREIGN KEY (user_id) REFERENCES users (user_id),
    CONSTRAINT fk_answer_comments_parent
        FOREIGN KEY (parent_comment_id) REFERENCES answer_comments (comment_id),
    CONSTRAINT fk_answer_comments_root
        FOREIGN KEY (root_comment_id) REFERENCES answer_comments (comment_id),
    CONSTRAINT fk_answer_comments_reply_user
        FOREIGN KEY (reply_to_user_id) REFERENCES users (user_id),
    CONSTRAINT ck_answer_comments_level CHECK (comment_level >= 1),
    CONSTRAINT ck_answer_comments_status CHECK (status IN ('ACTIVE', 'HIDDEN', 'DELETED')),
    CONSTRAINT ck_answer_comments_reply_count CHECK (reply_count >= 0),
    CONSTRAINT ck_answer_comments_delete_time CHECK (
        delete_time IS NULL OR delete_time >= create_time
    )
);

PROMPT Creating FAVORITES...
CREATE TABLE favorites (
    favorite_id      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    user_id          NUMBER NOT NULL,
    question_id      NUMBER NOT NULL,
    favorite_time    DATE   DEFAULT SYSDATE NOT NULL,
    CONSTRAINT pk_favorites PRIMARY KEY (favorite_id),
    CONSTRAINT fk_favorites_user
        FOREIGN KEY (user_id) REFERENCES users (user_id),
    CONSTRAINT fk_favorites_question
        FOREIGN KEY (question_id) REFERENCES questions (question_id),
    CONSTRAINT uq_favorites_pair UNIQUE (user_id, question_id)
);

PROMPT Creating BROWSE_HISTORY...
CREATE TABLE browse_history (
    history_id      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    user_id         NUMBER NOT NULL,
    question_id     NUMBER NOT NULL,
    browse_time     DATE   DEFAULT SYSDATE NOT NULL,
    duration        NUMBER DEFAULT 0       NOT NULL,
    click_depth     NUMBER DEFAULT 1       NOT NULL,
    CONSTRAINT pk_browse_history PRIMARY KEY (history_id),
    CONSTRAINT fk_browse_history_user
        FOREIGN KEY (user_id) REFERENCES users (user_id),
    CONSTRAINT fk_browse_history_question
        FOREIGN KEY (question_id) REFERENCES questions (question_id),
    CONSTRAINT ck_browse_history_duration CHECK (duration >= 0),
    CONSTRAINT ck_browse_history_depth CHECK (click_depth >= 1)
);

PROMPT Creating SEARCH_HISTORY...
CREATE TABLE search_history (
    search_id       NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    user_id         NUMBER             NOT NULL,
    keyword         VARCHAR2(100 CHAR) NOT NULL,
    search_time     DATE               DEFAULT SYSDATE NOT NULL,
    CONSTRAINT pk_search_history PRIMARY KEY (search_id),
    CONSTRAINT fk_search_history_user
        FOREIGN KEY (user_id) REFERENCES users (user_id)
);

PROMPT Creating RECOMMENDATIONS...
-- 推荐结果表：保存已经生成的推荐候选和推荐原因。
-- rec_type/rec_source 用于解释推荐来源，便于用户中心和后台排查推荐结果。
CREATE TABLE recommendations (
    rec_id          NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    user_id         NUMBER             NOT NULL,
    question_id     NUMBER             NOT NULL,
    rec_type        VARCHAR2(50 CHAR)  NOT NULL,
    rec_source      VARCHAR2(50 CHAR),
    rec_reason      VARCHAR2(200 CHAR),
    rec_score       NUMBER(6,2)        DEFAULT 0 NOT NULL,
    rec_time        DATE               DEFAULT SYSDATE NOT NULL,
    status          VARCHAR2(20 CHAR)  DEFAULT 'ACTIVE' NOT NULL,
    CONSTRAINT pk_recommendations PRIMARY KEY (rec_id),
    CONSTRAINT fk_recommendations_user
        FOREIGN KEY (user_id) REFERENCES users (user_id),
    CONSTRAINT fk_recommendations_question
        FOREIGN KEY (question_id) REFERENCES questions (question_id),
    CONSTRAINT ck_recommendations_type CHECK (
        rec_type IN ('TAG_BASED', 'POPULARITY', 'HYBRID', 'MANUAL')
    ),
    CONSTRAINT ck_recommendations_source CHECK (
        rec_source IS NULL OR rec_source IN (
            'USER_TAG_PROFILE',
            'POPULARITY',
            'USER_ACTION',
            'ADMIN_RULE',
            'MANUAL'
        )
    ),
    CONSTRAINT ck_recommendations_status CHECK (
        status IN ('ACTIVE', 'EXPIRED', 'DISMISSED')
    ),
    CONSTRAINT ck_recommendations_score CHECK (rec_score >= 0)
);

PROMPT Creating USER_TAG_PROFILE...
-- 用户标签画像表：由用户行为聚合生成，用 weight 表示用户对某个标签的兴趣强度。
-- 推荐算法会优先匹配用户画像中权重较高的标签。
CREATE TABLE user_tag_profile (
    profile_id      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    user_id         NUMBER      NOT NULL,
    tag_id          NUMBER      NOT NULL,
    weight          NUMBER(6,2) DEFAULT 0       NOT NULL,
    update_time     DATE        DEFAULT SYSDATE NOT NULL,
    CONSTRAINT pk_user_tag_profile PRIMARY KEY (profile_id),
    CONSTRAINT fk_user_tag_profile_user
        FOREIGN KEY (user_id) REFERENCES users (user_id),
    CONSTRAINT fk_user_tag_profile_tag
        FOREIGN KEY (tag_id) REFERENCES tags (tag_id),
    CONSTRAINT uq_user_tag_profile_pair UNIQUE (user_id, tag_id),
    CONSTRAINT ck_user_tag_profile_weight CHECK (weight >= 0)
);

PROMPT Creating CHAT_SESSION...
-- AI 追问会话表：围绕某个问题的 AI 首答继续追问。
-- seed_answer_id 指向被追问的 AI 首答，保证多轮对话有明确上下文。
CREATE TABLE chat_session (
    session_id      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    user_id         NUMBER            NOT NULL,
    question_id     NUMBER            NOT NULL,
    seed_answer_id  NUMBER            NOT NULL,
    start_time      DATE              DEFAULT SYSDATE NOT NULL,
    end_time        DATE,
    status          VARCHAR2(20 CHAR) DEFAULT 'OPEN' NOT NULL,
    CONSTRAINT pk_chat_session PRIMARY KEY (session_id),
    CONSTRAINT fk_chat_session_user
        FOREIGN KEY (user_id) REFERENCES users (user_id),
    CONSTRAINT fk_chat_session_question
        FOREIGN KEY (question_id) REFERENCES questions (question_id),
    CONSTRAINT fk_chat_session_seed_answer
        FOREIGN KEY (question_id, seed_answer_id)
        REFERENCES answers (question_id, answer_id),
    CONSTRAINT ck_chat_session_status CHECK (status IN ('OPEN', 'CLOSED', 'ARCHIVED')),
    CONSTRAINT ck_chat_session_time CHECK (
        end_time IS NULL OR end_time >= start_time
    )
);

PROMPT Creating CHAT_MESSAGE...
CREATE TABLE chat_message (
    message_id      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    session_id      NUMBER            NOT NULL,
    sender_type     VARCHAR2(20 CHAR) NOT NULL,
    content         CLOB              NOT NULL,
    send_time       DATE              DEFAULT SYSDATE NOT NULL,
    model_name      VARCHAR2(50 CHAR),
    CONSTRAINT pk_chat_message PRIMARY KEY (message_id),
    CONSTRAINT fk_chat_message_session
        FOREIGN KEY (session_id) REFERENCES chat_session (session_id),
    CONSTRAINT ck_chat_message_sender CHECK (sender_type IN ('USER', 'AI', 'SYSTEM'))
);

PROMPT Creating AI_PROMPT_LOG...
-- AI 调用日志表：保存提示词、模型响应、token 用量和模型名称。
-- 主要用于调试 AI 首答、AI 分类、AI 标签和后续成本/质量分析。
CREATE TABLE ai_prompt_log (
    prompt_id        NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    question_id      NUMBER NOT NULL,
    prompt_text      CLOB   NOT NULL,
    response_text    CLOB,
    token_usage      NUMBER DEFAULT 0       NOT NULL,
    model_name       VARCHAR2(50 CHAR),
    generate_time    DATE   DEFAULT SYSDATE NOT NULL,
    CONSTRAINT pk_ai_prompt_log PRIMARY KEY (prompt_id),
    CONSTRAINT fk_ai_prompt_log_question
        FOREIGN KEY (question_id) REFERENCES questions (question_id),
    CONSTRAINT ck_ai_prompt_log_token_usage CHECK (token_usage >= 0)
);

PROMPT Creating LOGIN_LOG...
-- 登录日志表：记录登录成功、失败和锁定结果。
-- 成功登录会通过触发器同步 users.last_login_time。
CREATE TABLE login_log (
    log_id          NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    user_id         NUMBER            NOT NULL,
    login_time      DATE              DEFAULT SYSDATE NOT NULL,
    ip_address      VARCHAR2(50 CHAR),
    result          VARCHAR2(20 CHAR) NOT NULL,
    CONSTRAINT pk_login_log PRIMARY KEY (log_id),
    CONSTRAINT fk_login_log_user
        FOREIGN KEY (user_id) REFERENCES users (user_id),
    CONSTRAINT ck_login_log_result CHECK (
        result IN ('SUCCESS', 'FAILURE', 'LOCKED')
    )
);

PROMPT Creating OPERATION_LOG...
-- 操作日志表：记录管理员或关键用户操作，支撑后台审计。
CREATE TABLE operation_log (
    op_id           NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    user_id         NUMBER             NOT NULL,
    op_type         VARCHAR2(50 CHAR)  NOT NULL,
    op_content      VARCHAR2(200 CHAR) NOT NULL,
    op_time         DATE               DEFAULT SYSDATE NOT NULL,
    CONSTRAINT pk_operation_log PRIMARY KEY (op_id),
    CONSTRAINT fk_operation_log_user
        FOREIGN KEY (user_id) REFERENCES users (user_id)
);

PROMPT Creating indexes...
-- 索引设计：围绕首页列表、详情页、用户中心、搜索历史、推荐和后台管理的高频查询字段建立。
-- 这些索引减少多表 JOIN、分页、按时间排序和按用户过滤时的查询成本。
CREATE INDEX idx_users_avatar_media_id ON users (avatar_media_id);

CREATE INDEX idx_media_assets_uploader_id ON media_assets (uploader_user_id);
CREATE INDEX idx_media_assets_owner_ref ON media_assets (owner_type, owner_id, status, sort_order);
CREATE INDEX idx_media_assets_create_time ON media_assets (create_time);

CREATE INDEX idx_questions_user_id ON questions (user_id);
CREATE INDEX idx_questions_category_id ON questions (category_id);
CREATE INDEX idx_questions_status ON questions (status);
CREATE INDEX idx_questions_ask_time ON questions (ask_time);

CREATE INDEX idx_answers_question_id ON answers (question_id);
CREATE INDEX idx_answers_user_id ON answers (user_id);
CREATE INDEX idx_answers_generate_time ON answers (generate_time);
CREATE INDEX idx_answers_status ON answers (status);

CREATE INDEX idx_question_tags_question_id ON question_tags (question_id);
CREATE INDEX idx_question_tags_tag_id ON question_tags (tag_id);

CREATE INDEX idx_answer_feedback_answer_id ON answer_feedback (answer_id);
CREATE INDEX idx_answer_feedback_user_id ON answer_feedback (user_id);
CREATE INDEX idx_answer_feedback_feedback_time ON answer_feedback (feedback_time);

CREATE INDEX idx_answer_comments_answer_id ON answer_comments (answer_id);
CREATE INDEX idx_answer_comments_user_id ON answer_comments (user_id);
CREATE INDEX idx_answer_comments_parent_id ON answer_comments (parent_comment_id);
CREATE INDEX idx_answer_comments_root_id ON answer_comments (root_comment_id);
CREATE INDEX idx_answer_comments_create_time ON answer_comments (create_time);

CREATE INDEX idx_favorites_user_id ON favorites (user_id);
CREATE INDEX idx_favorites_question_id ON favorites (question_id);
CREATE INDEX idx_favorites_time ON favorites (favorite_time);

CREATE INDEX idx_browse_history_user_id ON browse_history (user_id);
CREATE INDEX idx_browse_history_question_id ON browse_history (question_id);
CREATE INDEX idx_browse_history_time ON browse_history (browse_time);

CREATE INDEX idx_search_history_user_id ON search_history (user_id);
CREATE INDEX idx_search_history_keyword ON search_history (keyword);
CREATE INDEX idx_search_history_time ON search_history (search_time);

CREATE INDEX idx_recommendations_user_id ON recommendations (user_id);
CREATE INDEX idx_recommendations_question_id ON recommendations (question_id);
CREATE INDEX idx_recommendations_status ON recommendations (status);
CREATE INDEX idx_recommendations_time ON recommendations (rec_time);

CREATE INDEX idx_user_tag_profile_user_id ON user_tag_profile (user_id);
CREATE INDEX idx_user_tag_profile_tag_id ON user_tag_profile (tag_id);

CREATE INDEX idx_chat_session_user_id ON chat_session (user_id);
CREATE INDEX idx_chat_session_question_id ON chat_session (question_id);
CREATE INDEX idx_chat_session_seed_answer_id ON chat_session (seed_answer_id);
CREATE INDEX idx_chat_session_status ON chat_session (status);
CREATE INDEX idx_chat_session_start_time ON chat_session (start_time);

CREATE INDEX idx_chat_message_session_id ON chat_message (session_id);
CREATE INDEX idx_chat_message_send_time ON chat_message (send_time);

CREATE INDEX idx_ai_prompt_log_question_id ON ai_prompt_log (question_id);
CREATE INDEX idx_ai_prompt_log_generate_time ON ai_prompt_log (generate_time);

CREATE INDEX idx_login_log_user_id ON login_log (user_id);
CREATE INDEX idx_login_log_time ON login_log (login_time);

CREATE INDEX idx_operation_log_user_id ON operation_log (user_id);
CREATE INDEX idx_operation_log_time ON operation_log (op_time);

PROMPT Table creation completed successfully.
